# Generated by Django 4.2.23 on 2025-08-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0002_department_deptpricestat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quartier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "arrondissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quartiers",
                        to="prices.arrondissement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuartierPriceStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avg_price_m2", models.IntegerField()),
                ("transaction_count", models.IntegerField(default=0)),
                (
                    "quartier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_stats",
                        to="prices.quartier",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quartier_price_stats",
                        to="prices.year",
                    ),
                ),
            ],
            options={
                "unique_together": {("quartier", "year")},
            },
        ),
    ]
